name: shreddem
version: '3.8'

services:
  shreddem:
    container_name: shreddem
    build: .
    ports:
      - "17811:17811"
    volumes:
      - shreddem_data:/root/.config/shreddem
    environment:
      - HOST=0.0.0.0
      - PORT=17811
    restart: unless-stopped

volumes:
  shreddem_data:
